version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - /home/callam/jellyfin/config:/config
      - /home/callam/jellyfin/cache:/cache
      - /media/hd/TV_Shows:/media/TV_Shows
      - /media/hd/Audiobooks:/media/Audiobooks
      - /media/hd/Lectures:/media/Lectures
      - /media/hd/Movies:/media/Movies
      - /media/hd/Home_Videos:/media/Home_Videos
      - /media/hd/Pictures:/media/Pictures
	    
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped